# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, default='', help_text='Specific details of this item, such as preferred model.', verbose_name='description')),
                ('url', models.URLField(blank=True, default='', help_text='A website showing the item.')),
                ('image', models.ImageField(blank=True, help_text='A photo or illustration.', null=True, upload_to='gift_registry/images')),
                ('one_only', models.BooleanField(default=True, help_text='When checked, remove item from list someone has chosen it. For some items, you may be happy to receive multiple.')),
                ('live', models.BooleanField(default=False, help_text='Make this item visible to public.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Giver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_registry.Gift')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='giver',
            unique_together=set([('gift', 'email')]),
        ),
    ]
