# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gift_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Events',
                'verbose_name': 'Event',
            },
        ),
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['title'], 'verbose_name': 'Gift', 'verbose_name_plural': 'Gifts'},
        ),
        migrations.AlterModelOptions(
            name='giver',
            options={'ordering': ['id'], 'verbose_name': 'Giver', 'verbose_name_plural': 'Givers'},
        ),
        migrations.RemoveField(
            model_name='gift',
            name='user',
        ),
        migrations.AlterField(
            model_name='gift',
            name='desc',
            field=models.TextField(blank=True, default='', help_text='Specific details of this item, such as preferred model.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, help_text='A photo or illustration.', null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='live',
            field=models.BooleanField(default=True, help_text='Make this item visible to public.', verbose_name='Live'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='one_only',
            field=models.BooleanField(default=True, help_text='When checked, remove item from list someone has chosen it. For some items, you may be happy to receive multiple.', verbose_name='One only'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='url',
            field=models.URLField(blank=True, default='', help_text='A website showing the item.', verbose_name='url'),
        ),
        migrations.AddField(
            model_name='gift',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='gift_registry.Event', verbose_name='Event'),
        ),
    ]
