# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry', '0002_auto_20191128_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='gift_registry.Event', verbose_name='Event'),
            preserve_default=False,
        ),
    ]
