# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry', '0003_auto_20191128_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Gift category',
                'verbose_name_plural': 'Gift categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gift',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_registry.GiftCategory', verbose_name='Gift category'),
        ),
    ]
