# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry', '0004_auto_20191128_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['category', 'title'], 'verbose_name': 'Gift', 'verbose_name_plural': 'Gifts'},
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
